x-zabbix-timescaledb-env: &zabbix-timescaledb-env
  DB_SERVER_HOST: zabbix-timescaledb
  POSTGRES_DB: zabbix
  POSTGRES_USER: zabbix
  POSTGRES_PASSWORD: zabbix
services:
  postgres:
    image: postgres:16.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=netty
      - POSTGRES_USER=netty
      - POSTGRES_PASSWORD=netty
    ports:
      - '5432:5432'
    volumes:
      - narvis-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - narvis-redis-data:/var/lib/redis
    environment:
      - PASSWORD=netty
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    restart: unless-stopped
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager:/config
      - alertmanager-data:/alertmanager/data
    command:
      - '--config.file=/config/alertmanager.yml'
      - '--web.config.file=/config/alertmanager-web.yml'
    extra_hosts:
      - host.docker.internal:host-gateway

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0.3
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - 10051:10051
    volumes:
      - zabbix-server-history-data:/var/lib/zabbix/export:z
    depends_on:
      - zabbix-timescaledb
    environment:
      << : [*zabbix-timescaledb-env]
      ZBX_CACHESIZE: 1G  # 4g for prod
      ZBX_EXPORTFILESIZE: 1G
      ZBX_EXPORTTYPE: history
      ZBX_HANODENAME: zabbix-server
      ZBX_HISTORYCACHESIZE: 1G
      ZBX_HISTORYINDEXCACHESIZE: 1G
      ZBX_MAXHOUSEKEEPERDELETE: 500000
      ZBX_NODEADDRESS: zabbix-server
      ZBX_STARTALERTERS: 10
      ZBX_STARTDBSYNCERS: 30
      ZBX_STARTDISCOVERERS: 2
      ZBX_STARTHTTPPOLLERS: 2
      ZBX_STARTPINGERS: 5
      ZBX_STARTPOLLERS: 200
      ZBX_STARTPOLLERSUNREACHABLE: 20
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTVMWARECOLLECTORS: 6
      ZBX_TIMEOUT: 30
      ZBX_TRENDCACHESIZE: 1G
      ZBX_UNAVAILABLEDELAY: 15
      ZBX_UNREACHABLEDELAY: 15
      ZBX_UNREACHABLEPERIOD: 45
      ZBX_VALUECACHESIZE: 1G  # 8g for prod
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0.3
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - ./data/zabbix:/var/lib/zabbix
    depends_on:
      - zabbix-timescaledb
    environment:
      << : [*zabbix-timescaledb-env]
      PHP_TZ: Asia/Shanghai
  zabbix-timescaledb:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: zabbix-timescaledb
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    volumes:
      - zabbix-timescaledb-data:/var/lib/postgresql/data
    environment:
      << : [*zabbix-timescaledb-env]

  # victoriametrics:
  #   image: victoriametrics/victoria-metrics:v1.97.1
  #   container_name: victoriametrics
  #   restart: unless-stopped
  #   ports:
  #     - 8428:8428
  #   volumes:
  #     - victoriametrics-data:/var/lib/victoria-metrics-data
  #   command:
  #     - "--envflag.enable"
  #     - "--storageDataPath=/var/lib/victoria-metrics-data"
  #     - "--retentionPeriod=2"  # keep data for 2 months
  #     - "--httpListenAddr=:8428"
  #     - "--search.setLookbackToStep=true"  #? https://docs.victoriametrics.com/troubleshooting/
  #     - "--search.cacheTimestampOffset=1h"  #? https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4070
  #     # - "--search.disableAutoCacheReset"  #? https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1570
  #     - "--search.latencyOffset=0" #? https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2061

  #     - "--httpAuth.username=${VICTORIA_METRICS_USER}"
  #     - "--httpAuth.password=${VICTORIA_METRICS_PASSWORD}"

volumes:
  zabbix-timescaledb-data:
  narvis-postgres-data:
  narvis-redis-data:
  zabbix-server-history-data:
  alertmanager-data: