// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Jeffry"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/intend/circuit-types": {
            "get": {
                "tags": [
                    "Intend"
                ],
                "summary": "Get list of CircuitTypes",
                "parameters": [
                    {
                        "type": "string",
                        "name": "circuit_type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "WAN",
                            "LAN"
                        ],
                        "type": "string",
                        "name": "connection_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/schemas.ListResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/schemas.CircuitType"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/intend/device-roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Intend"
                ],
                "summary": "Get list of device roles",
                "parameters": [
                    {
                        "type": "string",
                        "name": "abbreviation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/schemas.ListResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/schemas.DeviceRole"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login/password": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Username Password Login",
                "parameters": [
                    {
                        "description": "Username Password Login",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.Oauth2PasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/security.AccessToken"
                        }
                    }
                }
            }
        },
        "/org/organizations": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "Create organization",
                "parameters": [
                    {
                        "description": "Create organization",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.Organization"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.Organization"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.AuthConfig": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                }
            }
        },
        "schemas.CircuitType": {
            "type": "object",
            "properties": {
                "circuit_type": {
                    "type": "string"
                },
                "connection_type": {
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/schemas.I18n"
                }
            }
        },
        "schemas.DeviceRole": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/schemas.I18n"
                },
                "device_role": {
                    "type": "string"
                },
                "product_family": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "schemas.I18n": {
            "type": "object",
            "properties": {
                "en": {
                    "type": "string"
                },
                "zh": {
                    "type": "string"
                }
            }
        },
        "schemas.ListResponse": {
            "type": "object",
            "properties": {
                "results": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "schemas.Oauth2PasswordRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "domain_name": {
                    "type": "string"
                },
                "enterprise_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "schemas.Organization": {
            "type": "object",
            "required": [
                "active",
                "auth_type",
                "domain_name",
                "enterprise_code",
                "id",
                "license_count",
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "auth_config": {
                    "$ref": "#/definitions/schemas.AuthConfig"
                },
                "auth_type": {
                    "description": "0: local 1: slack 2: google 3: teams 4: github",
                    "type": "integer",
                    "maximum": 4,
                    "minimum": 0
                },
                "created_at": {
                    "type": "string"
                },
                "domain_name": {
                    "type": "string"
                },
                "enterprise_code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "license_count": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "security.AccessToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "integer"
                },
                "issued_at": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "integer"
                },
                "refresh_token_issued_at": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Narvis API",
	Description:      "Narvis OpenAPI for developers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
