jwt:
  secret_key: '9fdee1b8a3f18b7f86673938beec96e6'
  public_auth_key: '32fd7b3e502186a69b09bfad6eeb014b'
  algorithm: 'HS256'
  access_token_expired_minutes: 1440
  refresh_token_expired_minutes: 10080

zap:
  level: info
  prefix: '[narvis/server]'
  format: console # json or console
  show_line: true
  encode_level: LowercaseColorLevelEncoder
  stacktrace_key: stacktrace

postgres:
  host: localhost
  port: 5432
  username: narvis
  password: 215de447698a2397c9bb878f54f175d4
  db_name: narvis
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: "silent" # debug, silent

redis:
  user_cluster: false
  addr: 127.0.0.1:6379
  password: 14adbad48f023d00b7223860f057a886
  db: 0
  cluster_addrs:
    # - 127.0.0.1:6379
    # - 127.0.0.1:6379
    # - 127.0.0.1:6379
  
cors:
  mode: allow-all # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: example1.com
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-ID
      allow-methods: POST, GET, OPTIONS, DELETE, PUT, PATCH, HEAD
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type, X-Request-ID
      allow-credentials: true # 布尔值

    - allow-origin: example2.com
      allow-headers: content-type
      allow-methods: POST, GET, OPTIONS, DELETE, PUT, PATCH, HEAD
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type, X-Request-ID
      allow-credentials: true # 布尔值

sys:
  router_prefix: "/api/v1"
  base_url: "http://127.0.0.1:8000"

sentry:
  dsn: ""
  enable_tracing: true
  traces_sample_rate: 0.7
  release: "v0.0.1"

env: dev

zbx:
  url: "http://127.0.0.1:8088"
  token: 9c89bc0ebfbabcbfb4c93a3c139932496ed3699b2c03f40130bece6178264f3f # replace after init

vtm:
  url: "http://127.0.0.1:8428"
  username: narvis
  password: 2cf1876faac490e320c1c39698b01a34

atm:
  url: "http://127.0.0.1:9093"
  username: narvis
  password: df22af3b501608cd63616d86b0ac1d77

rmq:
  server_url: amqp://narvis-server:26cc7abbea97a17b9f7860ee0dabb051@localhost:5672/server
  proxy_url: amqp://narvis-proxy:851b090b967a89f802e72a0baf1d230e@localhost:5672/proxy