logging:
  formatter: console
postgres:
  host: localhost
  port: "5432"
  username: narvis
  password: 215de447698a2397c9bb878f54f175d4
  db_name: narvis
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: silent
jwt:
  secret_key: 9fdee1b8a3f18b7f86673938beec96e6
  public_auth_key: 414aed4f241504a3209222d4c82ceb3d36d1884a0b31902a3964920b8f0a8510
  algorithm: HS256
  access_token_expired_minutes: 1440
  refresh_token_expired_minutes: 10080
redis:
  host: localhost
  port: 6379
  password: 14adbad48f023d00b7223860f057a886
  db: 0
  use_cluster: false
  cluster_addr: []
cors:
  allowed_origins:
  - '*'
sys:
  server_port: 8000
  base_url: http://127.0.0.1:8000
sentry:
  dsn: ""
  enable_tracing: true
  trace_sample_rate: 0
  release: v0.0.1
env: on_prem
zbx:
  url: http://127.0.0.1:8088
  token: 8172c782a3e044efb905286377d7c622663d0e7036c6e0ea26fe2b0c3492a1f4
vtm:
  url: http://127.0.0.1:8428
  username: narvis
  password: 2cf1876faac490e320c1c39698b01a34
atm:
  url: http://127.0.0.1:9093
  username: narvis
  password: df22af3b501608cd63616d86b0ac1d77
rmq:
  host: localhost
  port: 15672
  username: narvis-server
  password: 26cc7abbea97a17b9f7860ee0dabb051
  server_url: amqp://narvis-server:26cc7abbea97a17b9f7860ee0dabb051@localhost:5672/server
  proxy_url: amqp://narvis-proxy:851b090b967a89f802e72a0baf1d230e@localhost:5672/proxy
bootstrap:
  organization: Narvis
  enterprise_code: narvis
  domain_name: portal.narvis.com
  admin_password: admin123456
  snmp_community: public
  snmp_port: 161
  snmp_timeout: 10
  cli_user: admin
  cli_password: admin123456
clickhouse:
  host: localhost
  port: "9000"
  username: narvis
  password: ed763fd77e9da0e9b2509b1fc01fadde
  database: narvis
  read_timeout: 10
  dial_timeout: 15
