name: Docker Image Build

on:
  release:
   types: [published]
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
     - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64, amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image (server)
        if: startsWith(github.event.release.tag_name, 'server-') || startsWith(github.event.release.tag_name, 'all-')
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: jeffry688/narvis-server:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            GOFLAGS=-ldflags="-w -s"
      
      - name: Build and push Docker image (client)
        if: startsWith(github.event.release.tag_name, 'client-') || startsWith(github.event.release.tag_name, 'all-')
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: jeffry688/narvis-proxy:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            GOFLAGS=-ldflags="-w -s"
      
      - name: Build and push Docker image (bootstrap)
        if: startsWith(github.event.release.tag_name, 'bootstrap-') || startsWith(github.event.release.tag_name, 'all-')
        uses: docker/build-push-action@v5
        with:
          context: ./cmd/bootstrap
          push: true
          tags: jeffry688/narvis-bootstrap:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            GOFLAGS=-ldflags="-w -s"
