name: Docker Image Build

on:
  release:
   types: [published]
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64, amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image (server)
        if: startsWith(github.event.release.tag_name, 'server-') || startsWith(github.event.release.tag_name, 'all-')
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t jeffry688/narvis-server:${{ github.event.release.tag_name }} -t jeffry688/narvis-server:latest \
            -f server/Dockerfile . \
            --build-arg GOFLAGS=-ldflags="-w -s" \
            --push
      
      - name: Build and push Docker image (proxy)
        if: startsWith(github.event.release.tag_name, 'proxy-') || startsWith(github.event.release.tag_name, 'all-')
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t jeffry688/narvis-proxy:${{ github.event.release.tag_name }} -t jeffry688/narvis-proxy:latest \
            -f client/Dockerfile . \
            --build-arg GOFLAGS=-ldflags="-w -s" \
            --push
      
      - name: Build and push Docker image (bootstrap)
        if: startsWith(github.event.release.tag_name, 'bootstrap-') || startsWith(github.event.release.tag_name, 'all-')
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t jeffry688/narvis-bootstrap:${{ github.event.release.tag_name }} -t jeffry688/narvis-bootstrap:latest \
            -f server/cmd/bootstrap/Dockerfile . \
            --build-arg GOFLAGS=-ldflags="-w -s" \
            --push
